---
admin_user: admin

# k3s server endpoint (Control Plane)
k3s_url: "https://192.168.0.61:6443"

k3s_token: "K1000192462c7dd1bd83ade9655484bedd7ad9ddde94f3afe12ec0fd87c4a1215e3::server:17be3820d41e006f74649474e4a46a60"

# SSH 키 경로 (admin 계정 기준)
ssh_key_path: "/home/{{ admin_user }}/.ssh/id_ed25519"
ssh_pub_path: "/home/{{ admin_user }}/.ssh/id_ed25519.pub"

# 검증 대상 신규 노드 이름 (kubectl get nodes 에 보이는 NAME)
k3s_new_node_name: "k3s-wk-02"

# 테스트 파드 이름
k3s_verify_test_pod: "hello-verify"

